// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reamp.Infrastructure;

#nullable disable

namespace Reamp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LogoAssetId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Agencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agencies_ContactEmail_NotEmpty", "LEN(LTRIM(RTRIM([ContactEmail]))) > 0");

                            t.HasCheckConstraint("CK_Agencies_ContactPhone_NotEmpty", "LEN(LTRIM(RTRIM([ContactPhone]))) > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.AgencyBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("AgencyId", "Slug")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("AgencyBranches", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgencyBranches_Address_Lat", "[Address_Latitude] IS NULL OR ([Address_Latitude] BETWEEN -90 AND 90)");

                            t.HasCheckConstraint("CK_AgencyBranches_Address_Lng", "[Address_Longitude] IS NULL OR ([Address_Longitude] BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_AgencyBranches_ContactEmail_NotEmpty", "LEN(LTRIM(RTRIM([ContactEmail]))) > 0");

                            t.HasCheckConstraint("CK_AgencyBranches_ContactPhone_NotEmpty", "LEN(LTRIM(RTRIM([ContactPhone]))) > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgencyBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBranchId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Agents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agents_Role_Valid", "[Role] >= 1 AND [Role] <= 3");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgencyBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgencyBranchId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("InviteeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TargetBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TargetRoleValue")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("InviteeEmail");

                    b.HasIndex("TargetEntityId", "Type");

                    b.HasIndex("InviteeEmail", "Status", "ExpiresAtUtc");

                    b.ToTable("Invitations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invitations_Status_Valid", "[Status] >= 0 AND [Status] <= 4");

                            t.HasCheckConstraint("CK_Invitations_Type_Valid", "[Type] >= 0 AND [Type] <= 1");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.OrganizationApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status", "Type");

                    b.ToTable("OrganizationApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationApplications_Status_Valid", "[Status] >= 0 AND [Status] <= 4");

                            t.HasCheckConstraint("CK_OrganizationApplications_Type_Valid", "[Type] >= 0 AND [Type] <= 1");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Skills")
                        .HasColumnType("int");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Staffs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Staffs_Role_Valid", "[Role] >= 1 AND [Role] <= 3");

                            t.HasCheckConstraint("CK_Staffs_Skills_Valid", "[Skills] >= 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LogoAssetId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("Studios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Studios_Address_Lat", "[Address_Latitude] IS NULL OR ([Address_Latitude] BETWEEN -90 AND 90)");

                            t.HasCheckConstraint("CK_Studios_Address_Lng", "[Address_Longitude] IS NULL OR ([Address_Longitude] BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_Studios_ContactEmail_NotEmpty", "LEN(LTRIM(RTRIM([ContactEmail]))) > 0");

                            t.HasCheckConstraint("CK_Studios_ContactPhone_NotEmpty", "LEN(LTRIM(RTRIM([ContactPhone]))) > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AvatarAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.HasIndex("AvatarAssetId");

                    b.ToTable("UserProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_FirstName_NotEmpty", "LEN(LTRIM(RTRIM([FirstName]))) > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Downloads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("MaxDownloads")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPackageId");

                    b.HasIndex("DeliveryPackageId", "Type");

                    b.ToTable("DeliveryAccess", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryAccess_Downloads_NonNegative", "[Downloads] >= 0");

                            t.HasCheckConstraint("CK_DeliveryAccess_MaxDownloads_Positive", "[MaxDownloads] IS NULL OR [MaxDownloads] > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPackageId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("DeliveryPackageId", "MediaAssetId", "VariantName")
                        .IsUnique();

                    b.ToTable("DeliveryItems", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WatermarkEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ListingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("DeliveryPackages", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryPackages_Title_NotEmpty", "LEN(LTRIM(RTRIM([Title]))) > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AvailableFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double?>("FloorAreaSqm")
                        .HasColumnType("float");

                    b.Property<double?>("LandAreaSqm")
                        .HasColumnType("float");

                    b.Property<int>("ListingType")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerAgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("OwnerAgencyId");

                    b.HasIndex("Price");

                    b.HasIndex("PropertyType");

                    b.HasIndex("Status", "ListingType");

                    b.ToTable("Listings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Listings_Price_Positive", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.ListingAgentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TeamOrOfficeName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("ListingId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("ListingAgentSnapshots", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.ListingMediaRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("ListingId", "IsCover")
                        .IsUnique()
                        .HasFilter("[IsCover] = 1");

                    b.HasIndex("ListingId", "Role", "SortOrder")
                        .IsUnique();

                    b.ToTable("ListingMediaRefs", (string)null);
                });

            modelBuilder.Entity("Reamp.Domain.Media.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OwnerStudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProcessStatus")
                        .HasColumnType("int");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("ProviderAssetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploaderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerStudioId");

                    b.HasIndex("ProcessStatus");

                    b.HasIndex("OwnerStudioId", "ChecksumSha256")
                        .IsUnique()
                        .HasFilter("[ChecksumSha256] IS NOT NULL");

                    b.HasIndex("Provider", "ProviderAssetId")
                        .IsUnique();

                    b.ToTable("MediaAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaAssets_Duration_Positive", "[DurationSeconds] IS NULL OR [DurationSeconds] > 0");

                            t.HasCheckConstraint("CK_MediaAssets_Size_Positive", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Media.Entities.MediaVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("int");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.HasIndex("MediaAssetId", "Name")
                        .IsUnique();

                    b.ToTable("MediaVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaVariants_Size_Positive", "[SizeBytes] IS NULL OR [SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Shoots.Entities.ShootOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedPhotographerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchedulingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("AssignedPhotographerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("Status");

                    b.HasIndex("StudioId");

                    b.ToTable("ShootOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShootOrders_Total_NotNegative", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Reamp.Domain.Shoots.Entities.ShootTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ScheduledEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShootOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShootOrderId");

                    b.HasIndex("Type", "Status");

                    b.ToTable("ShootTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShootTasks_Price_Positive", "[Price] IS NULL OR [Price] > 0");

                            t.HasCheckConstraint("CK_ShootTasks_Time", "[ScheduledStartUtc] IS NULL OR [ScheduledEndUtc] IS NULL OR [ScheduledEndUtc] > [ScheduledStartUtc]");

                            t.HasCheckConstraint("CK_ShootTasks_Type_NonNegative", "[Type] >= 0");
                        });
                });

            modelBuilder.Entity("Reamp.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Reamp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Agency", b =>
                {
                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.AgencyBranch", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.Agency", null)
                        .WithMany("Branches")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Reamp.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AgencyBranchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Address_Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Latitude");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Address_Line2");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Longitude");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Address_Postcode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("Address_State");

                            b1.HasKey("AgencyBranchId");

                            b1.HasIndex("City");

                            b1.ToTable("AgencyBranches");

                            b1.WithOwner()
                                .HasForeignKey("AgencyBranchId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Agent", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.AgencyBranch", null)
                        .WithMany()
                        .HasForeignKey("AgencyBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reamp.Domain.Accounts.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Accounts.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("Reamp.Domain.Accounts.Entities.Agent", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Client", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.AgencyBranch", null)
                        .WithMany()
                        .HasForeignKey("AgencyBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reamp.Domain.Accounts.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Accounts.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("Reamp.Domain.Accounts.Entities.Client", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Invitation", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.OrganizationApplication", b =>
                {
                    b.OwnsOne("Reamp.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Address_Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Line2");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_Postcode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_State");

                            b1.HasKey("OrganizationApplicationId");

                            b1.ToTable("OrganizationApplications");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationApplicationId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Staff", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Accounts.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("Reamp.Domain.Accounts.Entities.Staff", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Studio", b =>
                {
                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Reamp.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StudioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Address_Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Latitude");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Address_Line1");

                            b1.Property<string>("Line2")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Address_Line2");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Longitude");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Address_Postcode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("Address_State");

                            b1.HasKey("StudioId");

                            b1.HasIndex("City");

                            b1.ToTable("Studios");

                            b1.WithOwner()
                                .HasForeignKey("StudioId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.UserProfile", b =>
                {
                    b.HasOne("Reamp.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Reamp.Domain.Accounts.Entities.UserProfile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("AvatarAssetId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryAccess", b =>
                {
                    b.HasOne("Reamp.Domain.Delivery.Entities.DeliveryPackage", null)
                        .WithMany("Accesses")
                        .HasForeignKey("DeliveryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryItem", b =>
                {
                    b.HasOne("Reamp.Domain.Delivery.Entities.DeliveryPackage", null)
                        .WithMany("Items")
                        .HasForeignKey("DeliveryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryPackage", b =>
                {
                    b.HasOne("Reamp.Domain.Listings.Entities.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Shoots.Entities.ShootOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.Listing", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("OwnerAgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Reamp.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)");

                            b1.Property<string>("Line2")
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.ListingAgentSnapshot", b =>
                {
                    b.HasOne("Reamp.Domain.Listings.Entities.Listing", null)
                        .WithMany("AgentSnapshots")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.ListingMediaRef", b =>
                {
                    b.HasOne("Reamp.Domain.Listings.Entities.Listing", null)
                        .WithMany("MediaRefs")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Media.Entities.MediaVariant", b =>
                {
                    b.HasOne("Reamp.Domain.Media.Entities.MediaAsset", null)
                        .WithMany("Variants")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Shoots.Entities.ShootOrder", b =>
                {
                    b.HasOne("Reamp.Domain.Accounts.Entities.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Accounts.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("AssignedPhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reamp.Domain.Listings.Entities.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reamp.Domain.Accounts.Entities.Studio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Reamp.Domain.Shoots.Entities.ShootTask", b =>
                {
                    b.HasOne("Reamp.Domain.Shoots.Entities.ShootOrder", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ShootOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reamp.Domain.Accounts.Entities.Agency", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Reamp.Domain.Delivery.Entities.DeliveryPackage", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Reamp.Domain.Listings.Entities.Listing", b =>
                {
                    b.Navigation("AgentSnapshots");

                    b.Navigation("MediaRefs");
                });

            modelBuilder.Entity("Reamp.Domain.Media.Entities.MediaAsset", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Reamp.Domain.Shoots.Entities.ShootOrder", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
